version: 2
jobs:
 build:
     - image: neo4j:3.4.7
   
 test:
    docker:
     - image: neo4j:3.4.7

      
    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      # Download and cache dependencies

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # run tests!
      - run: mvn clean test
      - run: mvn clean integration-test

#      -run:
#          name: Send to CodeCov
#          command: bash <{curl -s https://codecov.io/bash}



